### ISSUE TITLE
Ingroup multiple outgroups how this works

### ISSUE THREAD

**Issue by FrancisNge** [chrisjackson-pellicle/paragone-nf#12]
Hi Chris,

Just curious with this concept, if we specify multiple ingroup-outgroups (e.g., 3 taxa), does this mean that all 3 taxa has to be detected in each gene for that gene to be included in the pipeline filtering steps or that only one of those 3 taxa will be taken into account? Just trying to see how we can best account for uneven sequence coverage, as not all outgroups have good sequence coverage.

Cheers
Francis

**Comment by chrisjackson-pellicle** [comment]
Hi Francis,

By 'ingroup-outgroups', do you mean 'internal' outgroups?

No, not all three outgroup taxa need to be present in a given gene tree for it to be processed by the algorithms that require outgroups (MO, RT) - only a single outgroup taxon is required. 

`paragone-nf` writes a report showing outgroup coverage for each locus. In the recently updated pipeline (which now wraps [ParaGone](https://github.com/chrisjackson-pellicle/ParaGone)) this report is located at `results/00_logs_and_reports/reports/outgroup_coverage_report.tsv`.

Note that to run the new version of the pipeline, you'll need to re-download all the required files (`paragone.nf`, `paragone.config`, and the Singularity container `hybpiper-paragone.sif` if you're using Singularity. The pipeline now supports using conda environments rather than Singularity, if that's preferred. There are also some changes to the parameter names and required parameters when running the pipeline - the documentation should be up to date.   

Cheers,

Chris
